version: '3.8'


services:
  db:
    image: postgres:14
    container_name: restapi_postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=restapi_db

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

