name: Tesе and SAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        working-directory: ./app
        run: go test ./... -v -mod=vendor

      - name: Run goseq (SAST)
        working-directory: ./app
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@v2.20.0
          gosec -v -mod=vendor -fmt=json -out=goseq-report.json ./...
          
      - name: Upload gosec report
        uses: actions/upload-artifact@v4
        with:
          name: gosec-report
          path: gosec-report.json
  
  
      

      



